added new feature of computer vs human
mishal23/Tic-Tac-Toe pull request #12
Opened 2024-06-09 18:14 UTC by user23052036

Hellow There!

I have added the requested new feature of tic-tac-toe game between human and computer.. and made some slight changes added functions to remove problematic input buffer.

Also made the code even more readable.
Please accept my pull request.

2024-06-09 18:18 UTC, user23052036 commented
Sir, could you please review my code please

2024-07-23 04:05 UTC, user23052036 commented
Bhaiyaa, if you could then please review my pull request.. I rechecked in my system and it is working fine.

2024-07-23 04:40 UTC, mishal23 requested changes

2024-07-23 04:40 UTC, mishal23 commented on Code.c
> +    printf("Type 3 to view leader board:-\n\n\n");
nit: please bring the new line character on the line 43 for consistency

2024-07-23 04:40 UTC, mishal23 commented on Code.c
> +                getchar();
scanf is already done, why do you need getchar?

2024-07-23 04:40 UTC, mishal23 commented on Code.c
> +                printf("My name is user23052036(AI-BOT) lets play o_O");
let's just keep it as AI-BOT

2024-07-23 06:13 UTC, user23052036 commented
made all the required changes as requested

2024-07-23 20:01 UTC, user23052036 commented
Video Demo of the working of human vs computer feature below!



https://github.com/user-attachments/assets/ea8a215b-318e-46db-8ff8-8bb9d99e955e

2024-07-24 07:32 UTC, user23052036 commented
Sir, could you please review and if possible then merge my code

2024-07-28 05:38 UTC, user23052036 commented
If you get time please review the pull request by this weekend 🙏

2024-07-28 06:31 UTC, mishal23 approved these changes

2024-07-28 06:32 UTC, merged